# Generated by Django 5.1.2 on 2024-11-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_rename_created_at_answer_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('serial_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='interview.company')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='interview.topic')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='interview.tutorial'),
        ),
    ]
