# Generated by Django 5.1.2 on 2024-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_tutorial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='serial_number',
            field=models.FloatField(),
        ),
    ]
