# Generated by Django 5.1.2 on 2024-11-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_tutorial_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
